//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_IPC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int idPartida { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> idAdversario { get; set; }
        public System.DateTime horaFecha { get; set; }
        public string tipoPartida { get; set; }
        public string estado { get; set; }
        public int turnos { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
