//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_IPC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ronda
    {
        public int idRonda { get; set; }
        public int idTorneo { get; set; }
        public int idPartida { get; set; }
        public int NumJuego { get; set; }
        public int NumRonda { get; set; }
    
        public virtual Partida Partida { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
