//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_IPC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public int idSala { get; set; }
        public int numeroSala { get; set; }
        public int idUsuario { get; set; }
        public string tipo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
