//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_IPC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneo
    {
        public int idTorneo { get; set; }
        public int idCreador { get; set; }
        public int participantes { get; set; }
        public string nombre { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
